<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Version>0.1.1</Version>
    <Authors>Rulewright Contributors</Authors>
    <Product>Rulewright</Product>
    <Copyright>Copyright (c) 2026 Rulewright Contributors</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>rules-engine;business-rules;dotnet;netstandard2.0;json</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/albahadly/Rulewright.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/albahadly/Rulewright</PackageProjectUrl>
    <PackageReadmeFile Condition="Exists('$(MSBuildProjectDirectory)/README.md')">README.md</PackageReadmeFile>
  </PropertyGroup>

</Project>
