<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Rulewright.Execution\Rulewright.Execution.csproj" />
    <ProjectReference Include="..\..\src\Rulewright.Extensions.Functions\Rulewright.Extensions.Functions.csproj" />
    <ProjectReference Include="..\..\src\Rulewright.Json.SystemText\Rulewright.Json.SystemText.csproj" />
  </ItemGroup>

</Project>
