<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Rulewright.Core\Rulewright.Core.csproj" />
    <ProjectReference Include="..\..\src\Rulewright.Serialization\Rulewright.Serialization.csproj" />
    <ProjectReference Include="..\..\src\Rulewright.Execution\Rulewright.Execution.csproj" />
    <ProjectReference Include="..\..\src\Rulewright.Json.SystemText\Rulewright.Json.SystemText.csproj" />
    <ProjectReference Include="..\..\src\Rulewright.Extensions.Functions\Rulewright.Extensions.Functions.csproj" />
  </ItemGroup>

</Project>
